- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/EducGradBatchGraduationApplication.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/DataConversionJobCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/ConversionSummaryDTO.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/DataConversionProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/DataConversionStudentReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/repository/ConvGradStudentRepository.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/DataConversionService.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/util/RestUtils.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/DataConversionStudentWriter.java
Refactored data conversion side to use WebClient, and access token retrieval is enhanced to avoid the expiry in the long run process.
> RestUtils is added to centralize all WebClient calls.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/DataConversionController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/ConvCourseRestrictions.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/repository/ConvCourseRestrictionRepository.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/DataConversionService.java
Update functionality is done for Code Conversion.
> Update functionality is done for Code Conversion.

- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/DataConversionServiceTest.java
- api/src/test/resources/schema.sql
Tables creation is added for native query validation in junit.
> schema.sql is added for junit.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/EducGradBatchGraduationApplication.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/DataConversionController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/entity/GradCourseRestrictionEntity.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/GradCourseRestriction.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/repository/GradCourseRestrictionRepository.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/DataConversionService.java
Clean up to rename entity name.
> Clean up to rename entity name.

- README.md
- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/repository/ConvGradStudentRepository.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/repository/GradCourseRestrictionRepository.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/DataConversionServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/DataConversionServiceWithMockRepositoryTest.java
More JUnit test cases are added.
> More Unit Tests

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/rest/RestUtils.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/util/EducGradBatchGraduationApiConstants.java
GRAD-1253 : correlationID is created for each student in Batch Process.
> GRAD-1253 : correlationID is created for each student in Batch Process.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/SchedulingController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/GradDashboardService.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/controller/SchedulingControllerTest.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/GradDashboardServiceTest.java
Bug fix on toggling batch jobs.
> Bug fix on toggling batch jobs.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/RecalculateProjectedGradRunErrorReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/RecalculateProjectedGradRunErrorRetryReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/RecalculateStudentErrorReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/RecalculateStudentErrorRetryReader.java
The total read count issue in summary is fixed.
> The total read count issue in summary is fixed.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/GradRunCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/TvrRunJobCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/rest/RestUtils.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/util/EducGradBatchGraduationApiConstants.java
- api/src/main/resources/application.yaml
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/util/RestUtilsTest.java
- api/src/test/resources/application.yaml
> GRAD2-1600 is implemented.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/BaseRunCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/BaseSummaryDTO.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/BasePartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/BaseReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/BaseSpecialRunReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/RegGradAlgPartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/SpcRegGradAlgPartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/TvrRunPartitioner.java
Fixed the retry counts for errored students in partitioner.
> Fixed the retry counts for errored students in partitioner.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/BatchJobResponse.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/BaseDistributionPartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/BasePartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/GradBatchHistoryService.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/GradBatchHistoryServiceTest.java
GRAD2-1671: handling username for user request job is enhanced as the batch job is now running asynchronously to lose it's user name in the http request.
> GRAD2-1671: handling username for user request job is enhanced.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/TaskDefinition.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherControllerTest.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/TaskDefinitionTest.java
> GRAD2-1729: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/JobProperName.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/JobSelection.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/TaskSelection.java
GRAD2-1528 : task is complete.
> GRAD2-1528 : task is complete.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/UserReqDistributionRunCompletionNotificationListener.java
User Request Distribution Run - Original Certificate OC
> GRAD2-1838

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/JobProperName.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/JobSelection.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/TaskSelection.java
GRAD2-1909: task is complete in the backend
> GRAD2-1909: task is complete in the backend

- .github/workflows/build.from.main.branch.deploy.to.dev.yml
- .github/workflows/build.from.release.branch.deploy.to.dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
- Dockerfile
- tools/openshift/api.dc.yaml
Grad Batch Graduation Api resource optimization is done.
> GRAD2-1947 Resource optimization

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/UserScheduledReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/GradService.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/util/EducGradBatchGraduationApiUtils.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/util/JsonTransformer.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/BlankDistributionRunWriter.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/DistributionRunWriter.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/PsiDistributionRunWriter.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/RegGradAlgBatchPerformanceWriter.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/TvrRunBatchPerformanceWriter.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/UserScheduledWriter.java
GRAD2-1968 : task is complete.
> GRAD2-1968 : task is complete.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/DistributionRunCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/DistributionRunPartitionerSupplemental.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/rest/RestUtils.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/util/EducGradBatchGraduationApiConstants.java
- api/src/main/resources/application.yaml
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherControllerTest.java
- api/src/test/resources/application.yaml
Year-End Disribution run (DISTRUN_YE) - reports School-Level (DISTREP_YE_SC) and District-Level (DISTREP_YE_SD)
> GRAD2-1850

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/TaskDefinition.java
> GRAD2-2005: bug fix

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/GradDashboardService.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/GradDashboardServiceTest.java
> GRAD2-1720: task is complete

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/UserReqPsiDistributionRunCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/rest/RestUtils.java
- api/src/main/resources/application.yaml
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/util/RestUtilsTest.java
Done with PSIRUN generation of flat files for FTP transmission mode
> Grad2-1931 Distribution PSI FTP

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/BaseProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/BlankDistributionRunProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/DistributionRunProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/PsiDistributionRunProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/UserScheduledProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/BaseReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/BlankDistributionRunBaseReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/DistributionRunBaseReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/PsiDistributionRunBaseReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/UserScheduledReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/BaseWriter.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/TvrRunBatchPerformanceWriter.java
- api/src/test/resources/application.yaml
> Grad2-1929 Refactoring/Linting

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/DistributionRunCompletionNotificationListener.java
GRAD2-2017: bug fix on the actual counts of distribution async run.
> GRAD2-2017: bug fix on the actual counts of distribution async run.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/EducGradBatchGraduationApplication.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/config/AsyncConfig.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/BaseDistributionRunCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/DistributionRunCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/DistributionService.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/GradBatchHistoryService.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/util/EducGradBatchGraduationApiUtils.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/DistributionRunWriter.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/config/AsyncConfig.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherControllerTest.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/DistributionServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/GradBatchHistoryServiceTest.java
> GRAD2-2110: task is complete

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/DistributionRunStatusUpdateProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/DistributionService.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/GradBatchHistoryService.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherControllerTest.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/DistributionServiceTest.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/GradBatchHistoryServiceTest.java
GRAD2-2110: refactored to avoid transaction timeout in updating distribution job status.
> GRAD2-2110: refactored to avoid transaction timeout in updating distribution job status.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/rest/RestUtils.java
> GRAD2-2157: task is complete

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/CertificateRegenerationRequest.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/RegenerateCertificatePartitioner.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherControllerTest.java
GRAD2-2240: task is completed.
> GRAD2-2240: task is completed.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/DistributionRunYearlyPartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/util/GradLocalDateTimeDeserializer.java
> Fix Filter

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/BaseDistributionRunCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/DistributionRunStatusUpdateProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/DistributionService.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/DistributionServiceTest.java
> GRAD2-2253: task is complete

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/BaseDistributionRunCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/DistributionRunCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/DistributionRunYearlyCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/DistributionRunYearlyNonGradCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/DistributionRunStatusUpdateProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/DistributionRunYearlyNonGradProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/DistributionRunYearlyNonGradPartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/rest/RestUtils.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/BaseYearEndWriter.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/DistributionRunYearlyNonGradWriter.java
GRAD2-2255: task is completed.
> GRAD2-2255: task is completed.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/DistributionRunStatusUpdateProcessor.java
GRAD2-2255: bug fix on updating transcript distribution date.
> GRAD2-2255: bug fix on updating transcript distribution date.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/DistributionRunStatusUpdateProcessor.java
Issue with Last Issued Date on GRAD, NOT-YET GRADUATED and PROJECTED GRADUATED reports for TSW
> GRAD2-2034

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/DistributionRunPartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/rest/RestUtils.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/GraduationReportService.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/ParallelDataFetch.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/util/EducGradBatchGraduationApiConstants.java
- api/src/main/resources/application.yaml
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/ParallelDataFetchTest.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/util/RestUtilsTest.java
- api/src/test/resources/application.yaml
GRAD2-2280: task is completed.
> GRAD2-2280: task is completed.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/DistributionRunYearlyNonGradPartitioner.java
GRAD2-2298: the issue is resolved.
> GRAD2-2298: the issue is resolved.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/DistributionResponse.java
GRAD2-2298: fixed the issue on the district report for yearly nongrad.
> GRAD2-2298: fixed the issue on the district report for yearly nongrad.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/BasePartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/DistributionRunPartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/DistributionRunSupplementalPartitioner.java
GRAD2-2295: task is completed.
> GRAD2-2295: task is completed.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/BasePartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/DistributionRunPartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/DistributionRunSupplementalPartitioner.java
Reverts bcgov/EDUC-GRAD-BATCH-GRADUATION-API#425
> Revert "GRAD2-2295: task is completed."

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/BasePartitioner.java
Reverts bcgov/EDUC-GRAD-BATCH-GRADUATION-API#428
> Revert "GRAD2-2308 - HD-21581-GRAD - P3 - GRAD Batch Processing - Select Stud…"

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/StudentSearchRequest.java
User Request Blank Certificate Adult Dogwood to Advanced Education fails
> GRAD2-1869

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/config/BatchJobLauncher.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/config/TaskSchedulerConfig.java
- api/src/main/resources/application.yaml
- api/src/test/resources/application.yaml
> GRAD2-2396: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/config/RestWebClient.java
Unexpected Internal Server Error for TVRs for Projected Non-Grads
> GRAD2-2408

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/config/BatchJobLauncher.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/repository/BatchGradAlgorithmJobHistoryRepository.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/repository/BatchGradAlgorithmStudentRepository.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/repository/BatchJobExecutionRepository.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/repository/BatchStepExecutionRepository.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/repository/StudentCredentialDistributionRepository.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/service/GradDashboardService.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/util/EducGradBatchGraduationApiConstants.java
- api/src/main/resources/application.yaml
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/service/GradDashboardServiceTest.java
- api/src/test/resources/application.yaml
> GRAD2-2430: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/SpecialRunCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/rest/RestUtils.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/util/RestUtilsTest.java
Fixed code for list of students
> Grad2-2434 Archived students user name corrected

- tools/config/update-configmap.sh
> GRAD2-2545: task is complete.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/CertificateRegenerationRequest.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/StudentSearchRequest.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/RegenerateCertificatePartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/RegenerateCertificateReader.java
Regenerate Certificate Process Modifications
> GRAD2-2570

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/DistributionRunProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/DistributionRunYearlyProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/rest/RestUtils.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/util/RestUtilsTest.java
HD-22859 (GRAD) YE Distribution run should direct Certificates to School at Graduation, not School of Record
> GRAD2-2377

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/UserReqDistributionRunCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/StudentCredentialDistribution.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/StudentSearchRequest.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/rest/RestUtils.java
(GRAD) Fix User Request Distribution Run options - Part 2 - CUR and Null Distribution Dates
> GRAD2-2580

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/util/EducGradBatchGraduationApiConstants.java
- api/src/main/resources/application.yaml
- api/src/test/resources/application.yaml
Done with endpoint replacements
> Grad2-2632 school api call is replaced with trax api

- api/src/main/resources/db/migration/1.0/V1.0.48__DML-UPDATE_DATA-BATCH_JOB_TYPE_CODE.sql
> Grad2-2812 Modified ARC students description

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/DistributionRunStatusUpdateProcessor.java
GRAD2-2901: put error logs on distribution dates not being updated after distribution run
> GRAD2-2901: put error logs on distribution dates not being updated

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/JobProperName.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/JobSelection.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/TaskSelection.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherControllerTest.java
GRAD2-2283: user scheduled strings are added for archive batch processes.
> GRAD2-2283: user scheduled strings are added for archive batch processes.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/ArchiveSchoolReportsPartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/ArchiveStudentsPartitioner.java
Students/School Reports Archive Process NPE fix
> GRAD2-2322/2283

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/ArchiveStudentsProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/ArchiveStudentsPartitioner.java
Students/School Reports Archive Process Update status of scheduled jobs. Duplicated code removal
> GRAD2-2283

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/ArchiveSchoolReportsProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/ArchiveSchoolReportsPartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/rest/RestUtils.java
School Reports Archive Process all reports by type.
> GRAD2-2322

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/ArchiveStudentsCompletionNotificationListener.java
TVR Delete Process - Backend Changes Endpoints
> GRAD2-2817

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/BaseRegenSchoolReportsCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/RegenSchoolReportsCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/JobProperName.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/JobSelection.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/SchoolReportsRegenSummaryDTO.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/SchoolReportsRegenerationRequest.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/TaskSelection.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/RegenerateSchoolReportsProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/RegenerateSchoolReportsPartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/RegenerateSchoolReportsReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/rest/RestUtils.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/RegenerateSchoolReportsWriter.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherControllerTest.java
- api/src/test/java/ca/bc/gov/educ/api/batchgraduation/util/RestUtilsTest.java
GRAD2-2822: School Report Regeneration Process - Backend Changes
> GRAD2-2822: School Report Regeneration Process - Backend Changes

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/BaseRunCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/StudentSearchRequest.java
User Distribution Run downloaded report files are empty
> GRAD2-2958

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/config/BatchJobConfig.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/RegenSchoolReportsCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/model/SchoolReportsRegenSummaryDTO.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/RegenerateSchoolReportsProcessor.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/BaseSchoolReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/EDWSnapshotSchoolReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/RegenerateSchoolReportsPartitioner.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/reader/RegenerateSchoolReportsReader.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/writer/RegenerateSchoolReportsWriter.java
GRAD2-2968: enable multi-partitioning to regenerate school reports in parallel.
>  GRAD2-2968: enable multi-partitioning to regenerate school reports in parallel.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/BaseRunCompletionNotificationListener.java
GRAD2-3012: User Request REGALG is fixed to show the correct update user & activity code in audit history
> GRAD2-3012: User Request REGALG is fixed to show the correct update user & activity code in audit history

- .github/dependabot.yml
- .github/workflows/build.from.developer.branch.deploy.to.dev.yml
- .github/workflows/build.from.main.branch.deploy.to.dev.yml
- .github/workflows/build.from.release.branch.deploy.to.dev.yml
> Grad2-3126 version upgraded

- .github/workflows/build.from.developer.branch.deploy.to.dev.yml
- .github/workflows/build.from.main.branch.deploy.to.dev.yml
- .github/workflows/build.from.release.branch.deploy.to.dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
- tools/openshift/api.dc.yaml
Updated from DeploymntConfig to Deployment
> Updated to Deployment from DeploymentConfig

- api/src/main/resources/application.yaml
- api/src/test/resources/application.yaml
GRAD2-3266: the issue is resolved.
> GRAD2-3266: the issue is resolved.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/listener/UserReqDistributionRunCompletionNotificationListener.java
- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/processor/DistributionRunStatusUpdateProcessor.java
GRAD2-3338: task is completed.
> GRAD2-3338: task is completed.

- api/src/main/java/ca/bc/gov/educ/api/batchgraduation/controller/JobLauncherController.java
> Grad2-3337 Date Range for TVR
